- defaults:
    link:
        relink: true

- clean: ['~']

- create: ['~/.config/alacritty/']

- shell:
  - [./bin/get-wallpapers, Getting wallpapers]

- link:
    ~/.config/alacritty/alacritty.yml: alacritty.yml
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.oh-my-zsh/custom/themes/sorbet.zsh-theme: oh-my-zsh/custom/themes/sorbet.zsh-theme
    ~/.tmux.conf:
    ~/.vim:
    ~/.vimrc:
    ~/.zshrc:
    ~/Pictures/Wallpapers:
        create: true
        path: wallpapers



- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [./bin/gnome-keys load, Loading GNOME keybindings]

