- defaults:
    link:
        relink: true

- clean: ['~']

- create: ['~/.config/alacritty/', '~/.local/share/applications', '~/.icons/']

- shell:
  - 
    command: ./bin/install-os-specific 
    stdin: true
    stdout: true
    stderr: true
  - [./bin/get-wallpapers, Getting wallpapers]

- link:
    ~/.config/alacritty/alacritty.toml: alacritty.toml
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.oh-my-zsh/custom/themes/sorbet.zsh-theme: oh-my-zsh/custom/themes/sorbet.zsh-theme
    ~/.tmux.conf:
    ~/.vim:
    ~/.vimrc:
    ~/.zshrc:
    ~/Pictures/Wallpapers:
        create: true
        path: wallpapers
    ~/.local/share/applications/obsidian.desktop: applications/obsidian.desktop
    ~/.local/share/applications/obsidian.png: applications/obsidian.png


- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [./bin/gnome-keys load, Loading GNOME keybindings]

- link:
    ~/.icons/Boston-Icons:
        create: true
        path: dist/Boston-Icons
