#!/bin/sh

sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

# Merge in user resources and keymaps
xrdb -merge "$HOME/.Xresources"
xmodmap "$HOME/.Xmodmap"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Fonts
xset +fp /usr/share/fonts/gohufont
xset +fp $HOME/.fonts

# Set polish keymap
plkey

# Wallpaper
wallshuf

# Start bspwm
sxhkd &
urxvt &
$HOME/.lemonbar/bar.sh & disown
exec bspwm
