#!/bin/sh

bspc config border_width        8
bspc config window_gap          18

bspc config normal_border_color   "#2b363c"
bspc config focused_border_color  "#2b363c"
bspc config presel_border_color   "#535e66"

bspc monitor -d I II III IV V

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config top_padding 14

bspc rule -a "*" border=off
bspc rule -a "gimp" floating=on
bspc rule -a Firefox desktop=^1
bspc rule -a Steam desktop=^5 floating=on
