#!/bin/sh

bspc config border_width        4
bspc config window_gap          18

bspc config normal_border_color   "#d0d0d0"
bspc config focused_border_color  "#f0f0f0"
bspc config presel_feedback_color "#f0f0f0"

bspc monitor -d I II III IV V

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config top_padding 14

bspc rule -a Firefox desktop=^1
bspc rule -a Subl3 border=off desktop=^2
bspc rule -a Gimp floating=on desktop=^4
bspc rule -a Steam desktop=^5 pseudo_tiled=on border=off
bspc rule -a URxvt border=off
