#!/bin/sh

bspc config border_width        8
bspc config window_gap          18

bspc config normal_border_color   "#EEEEEE"
bspc config focused_border_color  "#EEEEEE"
bspc config presel_border_color   "#FFFFFF"

bspc monitor -d I II III IV

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config top_padding 15

bspc rule -a "*" border off
