#!/bin/sh

bspc config border_width        4
bspc config window_gap          18

bspc config normal_border_color   "#c7c7c7"
bspc config focused_border_color  "#ffffff"
bspc config presel_feedback_color "#f0f0f0"

bspc monitor eDP1  -n 0 -d I  II  III  IV V
# Todo - enable double monitors
#bspc monitor HDMI1 -n 1 -d VI VII VIII IX X

bspc config split_ratio         0.7
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_mouse true
bspc config top_padding 14

bspc rule -a Firefox desktop=^1
bspc rule -a Subl3 border=off desktop=^2
bspc rule -a Gimp floating=on desktop=^4
bspc rule -a Steam desktop=^5 border=off
bspc rule -a Gnome-terminal border=off
